#  Template NodeJS build

#  This template allows you to validate your NodeJS code.
#  The workflow allows running tests and code linting on the default branch.

image: node:16

pipelines:
  default:
    - step:
        name: Build only
        runs-on: 
          - 'self.hosted'
          - 'linux.shell'
        deployment: test
        # trigger: manual  # Uncomment to make this a manual deployment.
        script:
          - echo "Deploying to test environment"
          - npm install
          - npm run build
          #- sudo cp -R dist/* /opt/naresh/ui/
  branches:
    master:
      - step:
          name: Build and Deploy for master branch
          runs-on: 
            - 'self.hosted'
            - 'linux.shell'
          script:
            - echo "Deploying to test master branch"
            - npm install
            - npm run build
            - sudo cp -R dist/* /opt/naresh/ui/
          
